In [30]:
import numpy as np
import pandas as pd


from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import json 
import pickle
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("drug.csv")
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [5]:
df['Sex'].value_counts().to_dict()

{'M': 104, 'F': 96}

In [6]:
df['BP'].value_counts().to_dict()

{'HIGH': 77, 'LOW': 64, 'NORMAL': 59}

In [8]:
df['Cholesterol'].value_counts().to_dict()

{'HIGH': 103, 'NORMAL': 97}

In [13]:
df['Sex'].replace({'M': 1, 'F': 0},inplace=True)

In [14]:
df['BP'].replace({'HIGH': 2, 'LOW': 0, 'NORMAL': 1},inplace=True)

In [15]:
df['Cholesterol'].replace({'HIGH': 1, 'NORMAL': 0},inplace=True)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    int64
 2   BP           200 non-null    int64
 3   Cholesterol  200 non-null    int64
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(4), object(1)
memory usage: 9.5+ KB

In [18]:
x=df.drop('Drug',axis=1)
y=df['Drug']

In [19]:
x

     Age  Sex  BP  Cholesterol  Na_to_K
0     23    0   2            1   25.355
1     47    1   0            1   13.093
2     47    1   0            1   10.114
3     28    0   1            1    7.798
4     61    0   0            1   18.043
..   ...  ...  ..          ...      ...
195   56    0   0            1   11.567
196   16    1   0            1   12.006
197   52    1   1            1    9.894
198   23    1   1            0   14.020
199   40    0   0            0   11.349

[200 rows x 5 columns]

In [20]:
y

0      DrugY
1      drugC
2      drugC
3      drugX
4      DrugY
       ...
195    drugC
196    drugC
197    drugX
198    drugX
199    drugX
Name: Drug, Length: 200, dtype: object

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [25]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [26]:
y_pred=model.predict(x_test)

In [29]:
print("Accuracy",accuracy_score(y_test,y_pred))

Accuracy 0.9

In [31]:
with open("logisticRegression.pkl",'wb') as f:
    pickle.dump(model,f)

In [32]:
label_encoding={'Sex':{'M': 1, 'F': 0},'BP':{'HIGH': 2, 'LOW': 0, 'NORMAL': 1},'Cholesterol':{'HIGH': 1, 'NORMAL': 0}}

In [33]:
label_encoding

{'Sex': {'M': 1, 'F': 0},
 'BP': {'HIGH': 2, 'LOW': 0, 'NORMAL': 1},
 'Cholesterol': {'HIGH': 1, 'NORMAL': 0}}

In [34]:
with open("label_encoding.json",'w') as f:
    json.dump(label_encoding,f)

In [36]:
label_encoding['Sex']['M']

1